### ISSUE TITLE
CompileTimeTracker fails to compile in Unity 5.6.1f1.

### ISSUE THREAD

**Issue by DucRP** [DarrenTsung/DTCompileTimeTracker#9]
![image](https://user-images.githubusercontent.com/1282821/31052444-83eb3916-a639-11e7-9e9b-bb062ba21cd9.png)

Does anyone know how to compile CompileTimeTracker? These two compilation error show when I try compiling CompileTimeTracker in Unity 5.6.1f1.

**Comment by DarrenTsung** [comment]
Hi DucRP, 

I'm also using Unity 5.6.1f1 and I don't see this compilation error. Lines 8 and 9 of EditorApplicationCompilationUtil.cs should look like:
```
7: public static class EditorApplicationCompilationUtil {
8:     public static event Action StartedCompiling = delegate {};
9:     public static event Action FinishedCompiling = delegate {};
```

Is that what you're seeing? From the error it sounds like maybe they got changed to UnityEvent instead of Action possibly?

Here's a link to the [EditorApplicationCompilationUtil.cs](https://github.com/DarrenTsung/compile-time-tracker/blob/master/CompileTimeTracker/Editor/Util/EditorApplicationCompilationUtil.cs) from latest master.

**Comment by DarrenTsung** [comment]
Closing due to inactivity.
